### PR TITLE
Footer style update

### PR DESCRIPTION
**Pull request by dvdn**
Footer style update
+ init. refacto inclusions html in php

### CODE REVIEW

**Comment by TeXitoi** [comment]
Please no! Depend on a php server just for footer inclusion is very sad!

**Comment by prhod** [comment]
Agreed, the purpose of this site is to be PHP Free.

**Comment by dvdn** [comment]
I understand, i'll update this PR (status WIP for now on)

**Comment by prhod** [comment]
thanks for the refacto, good for me

**Pull request merged**
